separation of ci and dev configs

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -6,27 +6,36 @@ trigger_map:
 - pull_request_source_branch: '*'
   workflow: ci
 workflows:
-  docker-compose-console:
+  _ci_finish:
     steps:
-    - script@1.1.3:
-        title: Do anything with Script step
+    - cache-push@0.9.3:
         inputs:
-        - content: |-
-            #!/bin/bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-
-            docker-compose build
-            docker-compose run --rm --service-ports app bash
-          opts: {}
-  ci:
+        - cache_paths: $HOME/.npm
+  _ci_setup:
     steps:
     - activate-ssh-key@3.1.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@3.4.1: {}
-    - change-workdir@1.0.1: {}
+    - cache-pull@0.9.1: {}
+    - script@1.1.3:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            npm install -g ionic cordova
+          opts: {}
+  build-android:
+    steps:
+    - change-workdir@1.0.1:
+        inputs:
+        - opts: {}
+          path: ./cutePuppyPics
+        - is_create_path: "false"
+          opts: {}
     - script@1.1.3:
         title: Do anything with Script step
         inputs:
@@ -37,5 +46,12 @@ workflows:
             # debug log
             set -x
 
-            # npm install -g ionic cordova
+            cordova platform add android
+            cordova build android
           opts: {}
+  ci:
+    before_run:
+    - _ci_setup
+    after_run:
+    - build-android
+    - _ci_finish
